-- 017_refactor_order_id_to_bigint.sql
-- Refactor orders.id from VARCHAR to auto-incrementing BIGINT

BEGIN;

-- 1. Create a sequence for the new IDs
CREATE SEQUENCE IF NOT EXISTS orders_id_seq;

-- 2. Add temporary columns to hold the new integer IDs
ALTER TABLE orders ADD COLUMN new_id BIGINT;
ALTER TABLE order_line_items ADD COLUMN new_order_id BIGINT;
ALTER TABLE webhook_events ADD COLUMN new_order_id BIGINT;

-- 3. Populate orders.new_id using the sequence
UPDATE orders SET new_id = nextval('orders_id_seq');

-- 4. Sync the new IDs to child tables by joining on the old string ID
UPDATE order_line_items SET new_order_id = orders.new_id
FROM orders WHERE order_line_items.order_id = orders.id;

UPDATE webhook_events SET new_order_id = orders.new_id
FROM orders WHERE webhook_events.order_id = orders.id;

-- 5. Data Integrity: Set external_order_id to NOT NULL as requested
-- First, ensure any potential empty strings are treated as NULL or handled
-- (We verified no NULLs exist, but let's be safe for constraints)
ALTER TABLE orders ALTER COLUMN external_order_id SET NOT NULL;

-- 6. Drop old foreign keys and primary keys
ALTER TABLE order_line_items DROP CONSTRAINT IF EXISTS order_line_items_order_id_fkey;
ALTER TABLE webhook_events DROP CONSTRAINT IF EXISTS webhook_events_order_id_fkey;
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_pkey;

-- 7. Drop old string ID columns
ALTER TABLE orders DROP COLUMN id;
ALTER TABLE order_line_items DROP COLUMN order_id;
ALTER TABLE webhook_events DROP COLUMN order_id;

-- 8. Rename new columns to standard names
ALTER TABLE orders RENAME COLUMN new_id TO id;
ALTER TABLE order_line_items RENAME COLUMN new_order_id TO order_id;
ALTER TABLE webhook_events RENAME COLUMN new_order_id TO order_id;

-- 9. Set new Primary Key for orders
ALTER TABLE orders ADD PRIMARY KEY (id);

-- 10. Set the column to be auto-incrementing
ALTER TABLE orders ALTER COLUMN id SET NOT NULL;
ALTER TABLE orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 11. Synchronize the identity sequence with the maximum existing ID
-- This ensures the next auto-incremented value starts after our manual imports
SELECT setval(pg_get_serial_sequence('orders', 'id'), COALESCE((SELECT MAX(id) FROM orders), 1), true);

-- 12. Re-create foreign keys with BIGINT types
ALTER TABLE order_line_items 
    ADD CONSTRAINT order_line_items_order_id_fkey 
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE;

ALTER TABLE webhook_events 
    ADD CONSTRAINT webhook_events_order_id_fkey 
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL;

-- 13. Clean up the temporary transition sequence
DROP SEQUENCE IF EXISTS orders_id_seq;

COMMIT;
