# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5e3d8f1d3f37682aa3941e2c7043ee97"
application_url = "https://shop-chat-agent.millennialperfumer.in"
embedded = true
name = "shop-chat-agent"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings"

[auth]
redirect_urls = [ "https://shop-chat-agent.millennialperfumer.in/api/auth" ]

[build]
automatically_update_urls_on_dev = true
