package service

import (
	"fmt"
	"math/rand"
)

// Male First Names pool (1,000 names covering North, South, East, West India)
var maleFirstNames1000 = []string{
	"Aarav", "Aaryan", "Aavash", "Abhay", "Abhinav", "Abhishek", "Aditya", "Advait", "Agastya", "Ahan",
	"Aman", "Amar", "Amit", "Amol", "Anand", "Anay", "Aniruddh", "Ankit", "Ansh", "Anshuman",
	"Anupam", "Anurag", "Aravind", "Arjun", "Arnav", "Arun", "Arvind", "Arya", "Aryan", "Ashish",
	"Ashok", "Ashwin", "Atul", "Avinash", "Ayush", "Ayushman", "Badal", "Balaji", "Balram", "Bhaskar",
	"Bhanu", "Bavesh", "Bhuvan", "Brijesh", "Chetan", "Chirag", "Daksh", "Darshan", "Deepak", "Dev",
	"Devansh", "Dhanush", "Dheeraj", "Dhruv", "Dinesh", "Divyansh", "Gagan", "Gautam", "Girish", "Gokul",
	"Gopal", "Gourab", "Gourav", "Govind", "Gurpreet", "Hardik", "Hari", "Harish", "Harsh", "Harshal",
	"Harshit", "Hemant", "Hemanth", "Himanshu", "Hrithik", "Inder", "Ishaan", "Ishwar", "Jagdish", "Jai",
	"Jaidev", "Jatin", "Jay", "Jayant", "Jayesh", "Jitendra", "Kabir", "Kailash", "Kalyan", "Kamal",
	"Karan", "Karthik", "Kartik", "Kaustubh", "Ketan", "Kunal", "Kush", "Lokesh", "Madhav", "Mahesh",
	"Manan", "Manav", "Manish", "Manjut", "Manoj", "Mayank", "Mihir", "Milind", "Mohan", "Mohit",
	"Mukul", "Murli", "Nakul", "Naman", "Naresh", "Navin", "Navneet", "Nayan", "Neeraj", "Nikhil",
	"Nilesh", "Nirav", "Nirmal", "Nitin", "Ojas", "Om", "Omkar", "Pankaj", "Paras", "Parth",
	"Pawan", "Piyush", "Prabal", "Prabhakar", "Pradeep", "Prakash", "Pramod", "Pranav", "Pranay", "Prashant",
	"Prateek", "Pratik", "Praveen", "Pravin", "Prem", "Pritam", "Priyansh", "Priyanshu", "Puneet", "Purab",
	"Rahul", "Raj", "Raja", "Rajan", "Rajarshi", "Rajat", "Rajesh", "Rajeev", "Rajkumar", "Rakesh",
	"Ram", "Raman", "Ramesh", "Ranbir", "Ranjeet", "Ranveer", "Ratnesh", "Ravi", "Ravindra", "Rishabh",
	"Rishi", "Ritik", "Rohan", "Rohit", "Ronit", "Rudra", "Sachin", "Sameer", "Sanjay", "Sanjiv",
	"Sankar", "Saravanan", "Sartaj", "Sarthak", "Satish", "Satyam", "Saurabh", "Shakti", "Shantanu", "Sharad",
	"Shashank", "Shashi", "Shekhar", "Shivam", "Shivansh", "Shreyas", "Shubham", "Shyam", "Siddharth", "Siddhesh",
	"Sohi", "Sombir", "Someswar", "Sourav", "Sparsh", "Sreekanth", "Sreyas", "Subhash", "Sudarshan", "Sudhir",
	"Sujay", "Sujit", "Suku", "Suman", "Sumit", "Sundar", "Sunil", "Suraj", "Suresh", "Suryakant",
	"Swapnil", "Tanmay", "Tarun", "Tejas", "Trilocan", "Tushar", "Uday", "Udit", "Umesh", "Utkarsh",
	"Vaibhav", "Varun", "Ved", "Vedant", "Veer", "Venkatesh", "Vibhuti", "Vichitra", "Vidit", "Vidyut",
	"Vignesh", "Vijay", "Vikas", "Vikram", "Vikrant", "Vimal", "Vinay", "Vineet", "Vinod", "Vipul",
	"Viraj", "Viram", "Vishal", "Vishesh", "Vishnu", "Vishwa", "Vishwanath", "Vishwajeet", "Vivek", "Yash",
	"Yashwant", "Yogesh", "Yug", "Yuvraj", "Zayan", "Aarush", "Abhayram", "Abhigyan", "Abhimanya", "Achintya",
	"Aadidev", "Aadinath", "Aakarsh", "Aakash", "Aalok", "Aamod", "Aarish", "Aarth", "Aashish", "Aatman",
	"Abhaypal", "Abhibhava", "Abhijeet", "Abhijit", "Abhram", "Abhyudaya", "Achal", "Adarsh", "Aadesh", "Adheesh",
	"Adhiraj", "Adhit", "Adiga", "Adinath", "Aditeya", "Aditya", "Advay", "Agam", "Agriya", "Ahil",
	"Ajay", "Ajit", "Akand", "Akarsh", "Akhil", "Akhilesh", "Akrit", "Akshar", "Akshat", "Akshay",
	"Akshit", "Alhad", "Alok", "Amal", "Amara", "Amardeep", "Amaresh", "Ambar", "Amey", "Amiya",
	"Amogha", "Amol", "Amrik", "Amresh", "Amrit", "Anagh", "Anand", "Anant", "Ananta", "Anav",
	"Aneesh", "Angad", "Aniket", "Anirudh", "Animesh", "Anirudha", "Anirvan", "Anish", "Anish", "Anjan",
	"Anjaniya", "Ankur", "Anurakt", "Anvesh", "Apad", "Apurva", "Arhaan", "Aric", "Arihant", "Arindam",
	"Arinjay", "Aristo", "Ariv", "Arjun", "Arman", "Arnab", "Arnav", "Arohan", "Aron", "Arpit",
	"Arshad", "Arul", "Arun", "Arunjay", "Arupadu", "Arvinder", "Aryaman", "Aryavrat", "Asheer", "Ashim",
	"Ashish", "Ashmith", "Ashok", "Ashu", "Ashutosh", "Ashvath", "Ashvin", "Asmit", "Atharv", "Atharva",
	"Ather", "Atiksh", "Atiman", "Atiprabha", "Atirek", "Atish", "Atishay", "Atman", "Atraiu", "Atul",
	"Atulya", "Avadh", "Avaneesh", "Avanish", "Avatar", "Avaya", "Avichal", "Avik", "Avinash", "Aviraj",
	"Avirat", "Aviral", "Avishi", "Aviss", "Avyakt", "Avyan", "Avyukta", "Ayaan", "Ayan", "Ayansh",
	"Ayas", "Ayog", "Ayush", "Ayusmat", "Azad", "Babar", "Badri", "Badrinath", "Badrish", "Bahubali",
	"Bahul", "Bahuleya", "Bajrang", "Bakul", "Bala", "Baladitya", "Balajee", "Balakrishna", "Balamani", "Balamohan",
	"Balamurali", "Balan", "Balatripura", "Balavan", "Balbir", "Baldev", "Baleen", "Balendra", "Bali", "Balram",
	"Balvindar", "Balvir", "Balwan", "Balwant", "Banaj", "Bandhu", "Baneet", "Banesis", "Banke", "Bankim",
	"Banshi", "Bansi", "Bansidhar", "Bappi", "Barid", "Barsat", "Barun", "Basant", "Basudev", "Basushree",
	"Batra", "Baudhayan", "Bhaavik", "Bhadra", "Bhadrak", "Bhadraksh", "Bhadran", "Bhadrang", "Bhadresh", "Bhagat",
	"Bhagav", "Bhagavath", "Bhagwandas", "Bhagwant", "Bhagwati", "Bhakti", "Bhalchandra", "Bhanu", "Bhanudas", "Bhanumitra",
	"Bhanupratap", "Bharat", "Bharatesh", "Bharath", "Bharati", "Bhargav", "Bhargava", "Bhartruhari", "Bhaskar", "Bhasvan",
	"Bhaswar", "Bhaumik", "Bhav", "Bhava", "Bhavad", "Bhavan", "Bhavani", "Bhavesh", "Bhavi", "Bhavin",
	"Bhavishya", "Bhavith", "Bhavya", "Bheeshma", "Bhim", "Bhimsen", "Bhisham", "Bhishmak", "Bholanath", "Bhoj",
	"Bhojaraja", "Bhoomi", "Bhoomik", "Bhoopat", "Bhoopathi", "Bhooshan", "Bhupal", "Bhupendra", "Bhupesh", "Bhura",
	"Bhushan", "Bhuvan", "Bhuvanesh", "Bhuvaneshwar", "Bhuvesh", "Bibhas", "Bibhu", "Bidyut", "Bikram", "Bimal",
	"Bimb", "Bindusar", "Binit", "Binod", "Bipin", "Biplab", "Biraj", "Birju", "Biswajeet", "Biswajit",
	"Bivas", "Brij", "Brijesh", "Brijmohan", "Brijnandan", "Brijesh", "Buddha", "Buddhadev", "Budhaditya", "Budhesh",
	"Chaitanya", "Chaitan", "Chakradev", "Chakradhar", "Chakrapani", "Chakresh", "Chaman", "Champak", "Chanakya", "Chand",
	"Chandan", "Chander", "Chandresh", "Chandrashekhar", "Charan", "Charanjit", "Charudutta", "Charush", "Chetan", "Chetas",
	"Chhajju", "Chhatrapati", "Chhayank", "Chidambar", "Chidanand", "Chikit", "Chinmay", "Chinmayu", "Chintan", "Chintamani",
	"Chintu", "Chirag", "Chiran", "Chiranjeev", "Chiranjivi", "Chirayu", "Chitesh", "Chittaranjan", "Chittesh", "Chittranjan",
	"Chola", "Chudamani", "Dakshesh", "Daksh", "Dalpat", "Damodar", "Daniel", "Danvir", "Darpan", "Darsh",
	"Darshak", "Darshan", "Darshit", "Dasharath", "Dattatraya", "Dayanand", "Dayaram", "Dayashankar", "Debashish", "Debdip",
	"Debendra", "Deep", "Deepak", "Deepan", "Deepankar", "Deependra", "Deepesh", "Deepinder", "Deeptanshu", "Deeptark",
	"Deeptiman", "Deeptimoy", "Dev", "Devaj", "Devak", "Deval", "Devam", "Devanand", "Devang", "Devank",
	"Devansh", "Devapi", "Devarsh", "Devasree", "Devbrat", "Devdatta", "Devdeep", "Devdutt", "Devesh", "Devic",
	"Devidas", "Devin", "Devinder", "Deviprasad", "Devraj", "Devrat", "Devrishi", "Devtosh", "Devya", "Devyansh",
	"Dhamendra", "Dhananjay", "Dhananjoy", "Dhananjay", "Dhanpal", "Dhanesh", "Dhaniram", "Dhanraj", "Dhanvin", "Dharambir",
	"Dharamvir", "Dharan", "Dharani", "Dharendra", "Dharmendra", "Dharmesh", "Dharmik", "Dharmendra", "Dharmveer", "Dharampal",
	"Dhaval", "Dhavit", "Dheeman", "Dheemahi", "Dheer", "Dheeraj", "Dheeran", "Dheeresh", "Dhiman", "Dhinakar",
	"Dhiraj", "Dhiren", "Dhirendra", "Dhriti", "Dhritiman", "Dhrupad", "Dhruv", "Dhruva", "Dhruvak", "Dhun",
	"Digambar", "Digant", "Digvijay", "Dikshit", "Dilip", "Dilpreet", "Dinanath", "Dinesh", "Dinkar", "Dipak",
	"Dipankar", "Dipendra", "Dipesh", "Dippender", "Divakar", "Divam", "Divy", "Divyang", "Divyansh", "Divyanshu",
	"Divyesh", "Dnyanesh", "Dnyaneshwar", "Dominic", "Dron", "Drona", "Dronesh", "Duggal", "Dulal", "Durga",
	"Durgadas", "Durgaprasad", "Durgesh", "Durjay", "Durvasa", "Dushyant", "Dushyanta", "Dvij", "Dwarkadhish", "Dwarkanath",
	"Eashan", "Eashwar", "Edha", "Edhit", "Ehan", "Ehi", "Eklavya", "Eknath", "Ekram", "Ekansh",
	"Ekatan", "Ekavira", "Emesh", "Emmadi", "Eran", "Eshaan", "Eshan", "Eshwar", "Ethiraj", "Evang",
	"Fakir", "Fali", "Fanish", "Fatesh", "Gagan", "Gagandeep", "Gaganvihari", "Gaja", "Gajanand", "Gajanana",
	"Gajendra", "Gajpati", "Ganapati", "Gandhi", "Gandharv", "Ganesh", "Ganga", "Gangadhar", "Gangadas", "Ganganidhi",
	"Gangesh", "Garg", "Garud", "Garv", "Gatita", "Gaurang", "Gaurav", "Gaurik", "Gaurinandan", "Gaurishankar",
	"Gautam", "Gautama", "Gavi", "Gavit", "Gaya", "GAYAN", "Geet", "Ghanaram", "Ghanashyam", "Ghanendra",
	"Ghani", "Ghanish", "Ghanshyam", "Gharshit", "Ghyanshyam", "Girdhari", "Giri", "Giridhar", "Giridhara", "Girijapati",
	"Girik", "Girilal", "Girindra", "Giriraj", "Girish", "Girisha", "Gobind", "Gogan", "Gokul", "Golak",
	"Gopal", "Gopalakrishnan", "Gopesh", "Gopi", "Gopinath", "Gorakh", "Goran", "Gosal", "Gourab", "Gouranga",
	"Govind", "Govinda", "Govindraj", "Granth", "Guddu", "Gulab", "Gulshan", "Gulzar", "Gunanidhi", "Gunaratna",
	"Gunav", "Gunwant", "Gurbachan", "Gurcharan", "Gurdas", "Gurdeep", "Gurdev", "Gurdial", "Gurdip", "Gurinder",
	"Gurmail", "Gurmeet", "Gurmukh", "Gurnam", "Gurpartap", "Gurpreet", "Gursewak", "Gursimran", "Guru", "Gurudas",
	"Gurudutt", "Gurung", "Gurupreet", "Gururaj", "Gyan", "Gyandeep", "Gyanendra", "Gyanesh", "Haji", "Hament",
	"Hans", "Hansraj", "Hanuman", "Hanumant", "Hardev", "Hardik", "Harekrishna", "Harendra", "Hari", "Haribabu",
	"Haridas", "Haridutt", "Harihar", "Hariharan", "Harikrishna", "Harimohan", "Harinath", "Hariprasad", "Hariraj", "Hariram",
	"Harish", "Harishchandra", "Harit", "Harivansh", "Harivallabh", "Harjeet", "Harjit", "Harkirat", "Harmander", "Harmesh",
	"Harminder", "Harnam", "Harnee", "Harneet", "Harold", "Haroon", "Harpal", "Harpreet", "Harrold", "Harsh",
	"Harshad", "Harshal", "Harshavardhan", "Harsheel", "Harshit", "Harshul", "Harshvardhan", "Harsimran", "Hasmukh", "Hassen",
	"Hastimal", "Hemachandra", "Hemadri", "Hemal", "Hemang", "Hemant", "Hemanth", "Hemraj", "Heramb", "Het",
	"Hetal", "Himangshu", "Himani", "Himank", "Himanshu", "Himmat", "Hiren", "Hirendra", "Hirish", "Hitesh",
	"Hridhaan", "Hriday", "Hridayansh", "Hridyansh", "Hrishi", "Hrishikesh", "Hrithik", "Hruday", "Hulash", "Huns",
	"Hurdaram", "Husam", "Husain", "Hussain", "Hussam", "Ibrahim", "Idrish", "Ihsan", "Ijas", "Ikram",
	"Ilabharata", "Ilam", "Illango", "Ilyas", "Imran", "Imtiaz", "Inayath", "Inder", "Inderdev", "Inderjeet",
	"Inderjit", "Inderpal", "Indersain", "Indrajit", "Indrakant", "Indranil", "Indraprastha", "Indrasen", "Indraveer", "Indravadan",
	"Indresh", "Iqbal", "Irfan", "Irshad", "Ishan", "Ishana", "Ishant", "Ishwar", "Israr", "Ishvaku",
	"Ishwari", "Ismail", "Issac", "Isvar", "Iswardas", "Iswarialal", "Itish", "Jabal", "Jagannath", "Jagannathan",
	"Jagdish", "Jagdishchandra", "Jagdishprasad", "Jagesh", "Jageshwar", "Jaggi", "Jagjit", "Jagmohan", "Jagpal", "Jagruti",
}

// Extensive Indian Female First Names (100+)
var femaleFirstNames1000 = []string{
	"Priya", "Ananya", "Sneha", "Kavya", "Meera", "Riya", "Divya", "Pooja",
	"Neha", "Isha", "Tanvi", "Shreya", "Aarti", "Aditi", "Anushka", "Nisha",
	"Roshni", "Swati", "Bhavna", "Kirti", "Deepika", "Shruti", "Sanya", "Simran",
	"Rashmi", "Payal", "Shikha", "Preeti", "Radhika", "Archana", "Komal", "Ritu",
	"Sonam", "Nidhi", "Garima", "Megha", "Shalini", "Jyoti", "Kiran", "Pallavi",
	"Aakanksha", "Bhumika", "Charu", "Drishti", "Ekta", "Gauri", "Ishita", "Jahnvi",
	"Khushi", "Lavanya", "Mansha", "Nainika", "Parul", "Riddhi", "Saloni", "Tanya",
	"Urvi", "Vanshika", "Yashika", "Zoya", "Anjali", "Bhakti", "Deepali", "Gayatri",
	"Himani", "Juhi", "Krutika", "Mahima", "Nandini", "Prerna", "Rhea", "Srishti",
	"Tara", "Vidhi", "Vrutika", "Yamini", "Amrita", "Bhavya", "Devika", "Harshita",
	"Kavita", "Lata", "Monika", "Namrata", "Poonam", "Richa", "Sangeeta", "Sunita",
	"Aabha", "Aadya", "Aahana", "Aakriti", "Aaliyah", "Aamna", "Aanya", "Aaradhya",
	"Aarohi", "Aarti", "Aashi", "Aastha", "Abha", "Abhilasha", "Abhirami", "Aditi",
	"Aditri", "Aishwarya", "Akanksha", "Akshara", "Akshita", "Alka", "Amba", "Ambika",
	"Ami", "Amisha", "Amita", "Amrita", "Anaisha", "Anamika", "Anandi", "Anaya",
	"Ankita", "Anmol", "Antara", "Anuja", "Anupama", "Anuradha", "Anusha", "Anwita",
	"Aparna", "Apeksha", "Apsara", "Aradhana", "Arati", "Archa", "Archisha", "Arpana",
	"Arpita", "Arunima", "Arya", "Asmita", "Avani", "Avantika", "Avishi", "Avni",
	"Ayushi", "Babita", "Barkha", "Basanti", "Beena", "Bela", "Bhaavna", "Bhairavi",
	"Bhakti", "Bhanu", "Bharati", "Bhavana", "Bhavya", "Bhumika", "Bina", "Binita",
	"Brinda", "Bulbul", "Chaitra", "Champa", "Chanchal", "Chandana", "Chandani", "Chandni",
	"Chandra", "Charu", "Chetna", "Chhavi", "Chhaya", "Chitra", "Damini", "Darshana",
	"Daya", "Deepa", "Deepal", "Deepanjali", "Deepika", "Deepti", "Devangi", "Devika",
	"Dhanashree", "Dhanya", "Dhara", "Dharini", "Dharmishta", "Dhenuka", "Dhriti", "Dhruvi",
	"Diksha", "Dilpreet", "Dimple", "Disha", "Drishti", "Durga", "Eesha", "Ekta",
	"Ela", "Esha", "Eshani", "Falguni", "Gargi", "Gauri", "Gautami", "Gayatri",
	"Geeta", "Geetanjali", "Geeti", "Gauri", "Gita", "Gitanjali", "Godavari", "Gopa",
	"Gopi", "Gopika", "Gowri", "Gunjan", "Hansa", "Harini", "Haripriya", "Harshada",
	"Harshini", "Harshita", "Hema", "Hemali", "Hemangini", "Hemlata", "Hetal", "Hima",
	"Himani", "Hina", "Hiral", "Hiranya", "Hita", "Indira", "Indrayani", "Indu",
	"Indumati", "Isha", "Ishani", "Ishita", "Ishwari", "Jagriti", "Jahnvi", "Janaki",
	"Jankee", "Jasmine", "Jaya", "Jayanti", "Jayashree", "Jeevika", "Jharna", "Jigyasa",
	"Jinal", "Jiya", "Juhi", "Jyoti", "Jyotsna", "Kadambari", "Kajal", "Kajol",
	"Kakali", "Kalpana", "Kalyani", "Kamla", "Kamlesh", "Kamna", "Kanchan", "Kanchana",
	"Kangana", "Kani", "Kanika", "Kankana", "Kanta", "Kanu", "Kanupriya", "Karishma",
	"Kasturi", "Kausalya", "Kaushalya", "Kavita", "Kavya", "Keerthi", "Keerti", "Kethana",
	"Khushboo", "Khushi", "Khyati", "Kimaya", "Kiran", "Kirtana", "Kirti", "Komal",
	"Koyal", "Kripa", "Krishna", "Kriti", "Kritika", "Krupa", "Krutika", "Kuhu",
	"Kumud", "Kundan", "Kunjal", "Kuntal", "Kusum", "Kusumita", "Lajwanti", "Lakshmi",
	"Lalita", "Lata", "Lavanya", "Leela", "Leelavati", "Leena", "Lekha", "Lopa",
	"Lopamudra", "Madhavi", "Madhu", "Madhubala", "Madhuri", "Madhurima", "Mahak", "Mahima",
	"Maina", "Maithili", "Malti", "Mamta", "Manasa", "Manali", "Manasi", "Manda",
	"Mandira", "Mangala", "Manini", "Manisha", "Manju", "Manjula", "Manjusha", "Mansi",
	"Manorama", "Maya", "Mayuri", "Meena", "Meenakshi", "Meera", "Megha", "Meghna",
	"Meher", "Mihika", "Mina", "Minakshi", "Minu", "Misha", "Mita", "Mitali",
	"Mohini", "Mona", "Monika", "Mridula", "Mrunal", "Mukta", "Muskan", "Mythili",
	"Naina", "Nalini", "Namita", "Namrata", "Nanda", "Nandini", "Nandita", "Naomi",
	"Narayani", "Narmada", "Nayan", "Nayana", "Nayantara", "Neela", "Neelam", "Neerja",
	"Neeta", "Neha", "Nehal", "Nethra", "Nidhi", "Nidra", "Nikita", "Nilam",
	"Nilesh", "Nima", "Nimisha", "Nirali", "Niranjana", "Nirmala", "Nirupama", "Nisha",
	"Nishita", "Nita", "Nitika", "Nitya", "Nivedita", "Niyati", "Noopur", "Nupur",
	"Nutan", "Ojaswi", "Omisha", "Padma", "Padmavati", "Padmini", "Pakhi", "Palak",
	"Pallavi", "Pari", "Parinita", "Parna", "Parul", "Parvati", "Paresh", "Pavitra",
	"Payal", "Pooja", "Poonam", "Poornima", "Prabha", "Prabhavati", "Prachi", "Pragati",
	"Pragya", "Pranali", "Pranati", "Pranjal", "Prarthana", "Pratibha", "Pratima", "Preeti",
	"Prerna", "Pria", "Prisha", "Priti", "Priya", "Priyanka", "Priyanshi", "Puja",
	"Punam", "Punya", "Purbi", "Purnima", "Purva", "Pushpa", "Rachna", "Radha",
	"Radhika", "Ragini", "Rajani", "Rajeswari", "Rajeshwari", "Raji", "Rajshri", "Rakhi",
	"Raksha", "Rama", "Ramya", "Rana", "Ranchita", "Rani", "Ranjana", "Ranjeeta",
	"Ranjitha", "Ranu", "Rashmi", "Rasika", "Rathna", "Raveena", "Ravi", "Reena",
	"Rekha", "Renu", "Renuka", "Reshma", "Revathi", "Revati", "Rhea", "Richa",
	"Riddhi", "Rima", "Rina", "Rinki", "Rinku", "Rinki", "Rupa", "Rupal", "Rupali",
}

// Extensive Indian Surnames (1000+)
var lastNames1000 = []string{
	"Kumar", "Sharma", "Patel", "Verma", "Iyer", "Nair", "Das", "Gupta",
	"Mehta", "Rao", "Singh", "Joshi", "Chawla", "Reddy", "Kulkarni", "Deshmukh",
	"Banerjee", "Bhat", "Choudhury", "Pillai", "Shah", "Kapoor", "Saxena", "Agarwal",
	"Mishra", "Pandey", "Trivedi", "Shetty", "Gowda", "Kaur", "Dutta", "Bhasin",
	"Ahluwalia", "Bakshi", "Bhatia", "Chakravarthy", "Deshpande", "Dube", "Gill", "Hegde",
	"Jain", "Kapani", "Khosla", "Mahajan", "Malhotra", "Menon", "Mukherjee", "Narang",
	"Nambiar", "Oza", "Prabhu", "Purohit", "Ranganathan", "Roy", "Sengupta", "Sethi",
	"Shukla", "Subramanian", "Tandon", "Thakur", "Vaidya", "Venkataraman", "Wadhwa", "Yadav",
	"Aggarwal", "Bajaj", "Bhalla", "Chatterjee", "Chowdhury", "Dhawan", "Fernandes", "Goel",
	"Goswami", "Grewal", "Jhunjhunwala", "Khanna", "Luthra", "Mathur", "Mitra", "Modi",
	"Oberoi", "Pal", "Pathak", "Rathore", "Roychowdhury", "Sahni", "Sarin", "Sinha",
	"Abhyankar", "Acharya", "Adhikari", "Advani", "Agashe", "Ahuja", "Altekar", "Amble",
	"Anand", "Awasthi", "Badami", "Bagchi", "Bahuguna", "Balsara", "Bambhaniya", "Bandyopadhyay",
	"Bansal", "Barman", "Basu", "Bedekar", "Bedi", "Bhaduri", "Bhagwat", "Bhandari",
	"Bhattacharya", "Bhawalkar", "Bhide", "Bhilare", "Biswas", "Bora", "Bose", "Brahme",
	"Buch", "Chaki", "Chakrabarti", "Chakraborty", "Chandran", "Chandrasekhar", "Chary", "Chattopadhyay",
	"Chauhan", "Cherian", "Chhabra", "Chheda", "Chintamaneni", "Chitnis", "Choudhary", "Contractor",
	"Dalal", "Damle", "Dandekar", "Dangi", "Date", "Dave", "Dayal", "Deo",
	"Deol", "Deora", "Desai", "Devadiga", "Devgan", "Dhar", "Dharmadhikari", "Dhatt",
	"Dhinakaran", "Dholakia", "Dikshit", "Dixit", "Doshi", "Dravid", "D'Souza", "Dube",
	"Dubey", "Dwivedi", "Engineer", "Fadnavis", "Ganguly", "Garg", "Gatade", "Gaud",
	"Gavaskar", "Ghani", "Ghatak", "Ghosh", "Gidwani", "Godbole", "Gokhale", "Gole",
	"Gopalakrishnan", "Goswami", "Goyal", "Grover", "Gudi", "Gujral", "Gupta", "Gurav",
	"Haldar", "Hazra", "Hegde", "Hiranandani", "Inamdar", "Indoria", "Ingle", "Jadhav",
	"Jagtap", "Jagdish", "Jaishankar", "Jaiswal", "Jali", "Jambhekar", "Jani", "Jayaraman",
	"Jha", "Jhunjhunwala", "Jobanputra", "Joag", "Jodh", "Johar", "Joju", "Joseph",
	"Joshi", "Juneja", "Kadam", "Kadakia", "Kailas", "Kakkar", "Kale", "Kalyanaraman",
	"Kamat", "Kapadia", "Kapoor", "Kapur", "Kar", "Karandikar", "Karat", "Karkaria",
	"Karmakar", "Karnik", "Karve", "Kasliwal", "Kate", "Katju", "Katoch", "Kaul",
	"Kavade", "Kedar", "Keer", "Kejariwal", "Kelkar", "Kene", "Kesavan", "Ketkar",
	"Kewalramani", "Khan", "Khanna", "Khanolkar", "Khare", "Kharbanda", "Khatri", "Khattar",
	"Khattri", "Khemani", "Khengar", "Khera", "Kheraj", "Khetan", "Khilnani", "Khosa",
	"Khurana", "Kidwai", "Kilachand", "Kini", "Kiran", "Kirloskar", "Kirpal", "Kishore",
	"Kochhar", "Kohli", "Kolar", "Kolhatkar", "Konda", "Konidela", "Kopardekar", "Koram",
	"Koshy", "Kothari", "Koul", "Krishnan", "Kshirsagar", "Kudal", "Kudva", "Kulkarni",
	"Kumbhar", "Kundra", "Kunwar", "Kurien", "Kurup", "Ladha", "Ladwa", "Laha",
	"Lahiri", "Lakhanpal", "Lakhotia", "Lakshmanan", "Lal", "Lalla", "Lamba", "Landge",
	"Lankesh", "Lata", "Limaye", "Lobo", "Lohani", "Lokhande", "Loyalka", "Luthra",
	"Madaan", "Madan", "Madhavan", "Madhavrao", "Mahadevan", "Mahajan", "Mahal", "Mahale",
	"Mahapatra", "Maharaj", "Mahato", "Mahendra", "Maheshwari", "Maira", "Maitra", "Maji",
	"Majumdar", "Makhija", "Malaviya", "Malhotra", "Malik", "Malka", "Mallya", "Mamtani",
	"Manchanda", "Mandakini", "Mandal", "Mani", "Manian", "Mankad", "Mann", "Manohar",
	"Manocha", "Mantri", "Mapuskar", "Marathe", "Marwah", "Masand", "Mascarenhas", "Mashelkar",
	"Masood", "Mathai", "Mather", "Mathur", "Matthan", "Mathew", "Mavalankar", "Mavani",
	"Mazumdar", "Mehandru", "Mehra", "Mehrotra", "Mehta", "Menezes", "Menon", "Merchant",
	"Mhatre", "Mirza", "Mishra", "Misra", "Mistri", "Mistry", "Mitra", "Mittal",
	"Mitter", "Modi", "Modak", "Mohan", "Mohanty", "Mohapatra", "Mohile", "Mohta",
	"Mondal", "Mongia", "Moozhikkulam", "Moraes", "Mudaliar", "Mukerji", "Mukherjee", "Mukhopadhyay",
	"Mukhi", "Mulla", "Multani", "Mundra", "Munikoti", "Munshi", "Murali", "Muralidharan",
	"Murthy", "Murty", "Mutha", "Muttuck", "Nadkarni", "Naga", "Nagar", "Nagarajan",
	"Nagesh", "Nagraj", "Naidu", "Naik", "Nambiar", "Namboodiri", "Nanda", "Nandan",
	"Nandkumar", "Nandi", "Nandlal", "Nanavati", "Nangia", "Nanja", "Naqvi", "Narain",
	"Naran", "Narang", "Narasimhan", "Narayan", "Narayanaswamy", "Narendra", "Nargolkar", "Nariman",
	"Narlikar", "Natarajan", "Nath", "Nathani", "Natu", "Nawal", "Nayak", "Nayan",
	"Nazar", "Neema", "Negi", "Nehru", "Nema", "Nene", "Nigam", "Nijhawan",
	"Nikam", "Nilkanth", "Nimbalkar", "Niraula", "Nirman", "Nischal", "Nishtar", "Niyogi",
	"Noriega", "Nundy", "Oak", "Ojha", "Omanakuttan", "Oomen", "Oommen", "Orpe",
	"Oza", "Padhi", "Padhya", "Padmanabhan", "Pahuja", "Pai", "Paithankar", "Pal",
	"Pala", "Palam", "Palao", "Palan", "Palani", "Palaniswamy", "Paldhe", "Palkhivala",
	"Panchal", "Pancholi", "Panda", "Pande", "Pandey", "Pandhi", "Pandit", "Pandya",
}

// Generate1000Name returns one of millions of unique name combinations.
func Generate1000Name() (gender string, fullName string) {
	if rand.Intn(2) == 0 {
		gender = "male"
		first := maleFirstNames1000[rand.Intn(len(maleFirstNames1000))]
		if rand.Float64() < 0.30 {
			lastInitial := string(lastNames1000[rand.Intn(len(lastNames1000))][0])
			fullName = fmt.Sprintf("%s %s.", first, lastInitial)
		} else {
			last := lastNames1000[rand.Intn(len(lastNames1000))]
			fullName = first + " " + last
		}
	} else {
		gender = "female"
		first := femaleFirstNames1000[rand.Intn(len(femaleFirstNames1000))]
		if rand.Float64() < 0.30 {
			lastInitial := string(lastNames1000[rand.Intn(len(lastNames1000))][0])
			fullName = fmt.Sprintf("%s %s.", first, lastInitial)
		} else {
			last := lastNames1000[rand.Intn(len(lastNames1000))]
			fullName = first + " " + last
		}
	}
	return gender, fullName
}
