events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Nginx reverse proxy configuration
    # Docker's internal DNS resolver
    resolver 127.0.0.11 valid=30s;

    # SSL shared configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Frontend block (HTTPS)
    server {
        listen 443 ssl;
        server_name mi-tech.millennialperfumer.in;
        ssl_certificate /etc/letsencrypt/live/mi-tech.millennialperfumer.in/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mi-tech.millennialperfumer.in/privkey.pem;

        location / {
            set $frontend_upstream http://frontend:80;
            proxy_pass $frontend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # API block (HTTPS)
    server {
        listen 443 ssl;
        server_name mi-tech-api.millennialperfumer.in;
        ssl_certificate /etc/letsencrypt/live/mi-tech.millennialperfumer.in/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mi-tech.millennialperfumer.in/privkey.pem;

        location / {
            set $backend_upstream http://backend:8080;
            proxy_pass $backend_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # Monitoring block (HTTPS)
    server {
        listen 443 ssl;
        server_name mi-tech-monitoring.millennialperfumer.in;
        ssl_certificate /etc/letsencrypt/live/mi-tech-monitoring.millennialperfumer.in/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mi-tech-monitoring.millennialperfumer.in/privkey.pem;

        location / {
            set $grafana_upstream http://grafana:3000;
            proxy_pass $grafana_upstream;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    # HTTP to HTTPS Redirects & Certbot Challenges
    server {
        listen 80;
        server_name mi-tech.millennialperfumer.in mi-tech-api.millennialperfumer.in mi-tech-monitoring.millennialperfumer.in;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://$host$request_uri;
        }
    }
}
